### ISSUE TITLE
page not found - .htaccess missing in repository?

### ISSUE THREAD

**Issue by tomasnikl** [ChiarilloMassimo/PokemonGo-Farm#1]
Hi,

there is error if I click on "Config -> New".. redirect to: /PokemonGo-Farm/web/config/new and page not found... there is no .htaccess file.. it is ok?

**Comment by massimo-me** [comment]
Hey :) 

Are you using `web/index.php` as frontcontroller? Try to execute this command

`php -S 127.0.0.1:8080 -t web` 

If not work, i also added the .htaccess file https://github.com/ChiarilloMassimo/PokemonGo-Farm/commit/dbc9d9984f86f559c9d66d255bfd3f42514dad9b

**Comment by tomasnikl** [comment]
with command `php -S 127.0.0.1:8080 -t web` works OK ;) thank you
